apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: spannerdatabases.databaseadmins.spanner-operator.io
spec:
  group: databaseadmins.spanner-operator.io
  version: v1alpha1
  names:
    kind: SpannerDatabase
    plural: spannerdatabases
    shortNames:
      - spd
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            namespace:
              type: string
              pattern: 'spanner'
  additionalPrinterColumns:
    - name: InstanceId
      type: string
      description: The instance ref for the SpannerDatabase
      JSONPath: .spec.instanceId
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp