apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: testing
  namespace: operator
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: instanceadmins.spanner-operator.io/v1alpha1
    kind: SpannerInstance
    name: testing
  metrics:
  - external:
      metricName: spanner.googleapis.com|instance|cpu|utilization
      metricSelector:
        matchLabels:
          resource.labels.database: testing
      targetAverageValue: 0.60
    type: External